// <auto-generated />
using System;
using API.ApplicationDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(StaffDbContext))]
    [Migration("20241226091246_Store5")]
    partial class Store5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Model.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.ToTable("notes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fbe6317c-1439-48fc-8f69-9b8fbf9a8e48"),
                            DateCreated = new DateTime(2024, 12, 26, 16, 12, 45, 101, DateTimeKind.Local).AddTicks(9315),
                            Text = "Welcome Note"
                        },
                        new
                        {
                            Id = new Guid("ed66bc23-56d9-4c13-90ba-917b2ca55c82"),
                            DateCreated = new DateTime(2024, 12, 26, 16, 12, 45, 101, DateTimeKind.Local).AddTicks(9316),
                            Text = "Take note"
                        });
                });

            modelBuilder.Entity("Data.Model.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Salary")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loacation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a745ece2-e2db-43be-a24b-18c7647ed7b6"),
                            DateCreated = new DateTime(2024, 12, 26, 16, 12, 45, 101, DateTimeKind.Local).AddTicks(9196),
                            DateDeleted = new DateTime(2024, 12, 26, 16, 12, 45, 101, DateTimeKind.Local).AddTicks(9208),
                            DateOfBirth = new DateTime(1990, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 12, 26, 16, 12, 45, 101, DateTimeKind.Local).AddTicks(9205),
                            FirstName = "John",
                            Gender = "Male",
                            LastName = "Doe",
                            NickName = "Johnny",
                            Place = "New York",
                            Position = "Developer",
                            Salary = 50000.0,
                            Status = "Active",
                            loacation = ""
                        },
                        new
                        {
                            Id = new Guid("1a56d2a4-8213-4fd7-9ff4-4c22ba14d854"),
                            DateCreated = new DateTime(2024, 12, 26, 16, 12, 45, 101, DateTimeKind.Local).AddTicks(9233),
                            DateDeleted = new DateTime(2024, 12, 26, 16, 12, 45, 101, DateTimeKind.Local).AddTicks(9234),
                            DateOfBirth = new DateTime(1985, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 12, 26, 16, 12, 45, 101, DateTimeKind.Local).AddTicks(9234),
                            FirstName = "Jane",
                            Gender = "Female",
                            LastName = "Smith",
                            NickName = "Janey",
                            Place = "London",
                            Position = "Manager",
                            Salary = 60000.0,
                            Status = "Inactive",
                            loacation = ""
                        },
                        new
                        {
                            Id = new Guid("a009d280-4ab1-4c75-9fab-af15f5f97a2a"),
                            DateCreated = new DateTime(2024, 12, 26, 16, 12, 45, 101, DateTimeKind.Local).AddTicks(9237),
                            DateDeleted = new DateTime(2024, 12, 26, 16, 12, 45, 101, DateTimeKind.Local).AddTicks(9237),
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 12, 26, 16, 12, 45, 101, DateTimeKind.Local).AddTicks(9237),
                            FirstName = "John",
                            Gender = "",
                            LastName = "Doe",
                            NickName = "Johnny",
                            Place = "New York",
                            Position = "Designer",
                            Salary = 55000.0,
                            Status = "Active",
                            loacation = ""
                        },
                        new
                        {
                            Id = new Guid("ca0df4c8-9389-4240-9270-391a80ab98e6"),
                            DateCreated = new DateTime(2024, 12, 26, 16, 12, 45, 101, DateTimeKind.Local).AddTicks(9239),
                            DateDeleted = new DateTime(2024, 12, 26, 16, 12, 45, 101, DateTimeKind.Local).AddTicks(9240),
                            DateOfBirth = new DateTime(1987, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 12, 26, 16, 12, 45, 101, DateTimeKind.Local).AddTicks(9239),
                            FirstName = "Alice",
                            Gender = "",
                            LastName = "Johnson",
                            NickName = "Ally",
                            Place = "Los Angeles",
                            Position = "tester",
                            Salary = 70000.0,
                            Status = "Active",
                            loacation = ""
                        },
                        new
                        {
                            Id = new Guid("f4ee3099-1d30-4719-aba0-0aa597dc8893"),
                            DateCreated = new DateTime(2024, 12, 26, 16, 12, 45, 101, DateTimeKind.Local).AddTicks(9242),
                            DateDeleted = new DateTime(2024, 12, 26, 16, 12, 45, 101, DateTimeKind.Local).AddTicks(9242),
                            DateOfBirth = new DateTime(1992, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 12, 26, 16, 12, 45, 101, DateTimeKind.Local).AddTicks(9242),
                            FirstName = "Bob",
                            Gender = "",
                            LastName = "Brown",
                            NickName = "Bobby",
                            Place = "San Francisco",
                            Position = "Developer",
                            Salary = 65000.0,
                            Status = "Inactive",
                            loacation = ""
                        });
                });

            modelBuilder.Entity("Data.Model.Note", b =>
                {
                    b.HasOne("Data.Model.Staff", "Staff")
                        .WithMany("notes")
                        .HasForeignKey("StaffId");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Data.Model.Staff", b =>
                {
                    b.Navigation("notes");
                });
#pragma warning restore 612, 618
        }
    }
}
