// <auto-generated />
using System;
using API.ApplicationDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(StaffDbContext))]
    [Migration("20241226070046_Store1")]
    partial class Store1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Model.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.ToTable("notes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4fb65b1f-e856-4ef3-91f7-e706a875cc2e"),
                            DateCreated = new DateTime(2024, 12, 26, 14, 0, 46, 302, DateTimeKind.Local).AddTicks(8021),
                            Text = "Welcome Note"
                        });
                });

            modelBuilder.Entity("Data.Model.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<double?>("Salary")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loacation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc0fbf76-5780-4a93-9b6c-819d9151aef3"),
                            DateCreated = new DateTime(2024, 12, 26, 14, 0, 46, 302, DateTimeKind.Local).AddTicks(7902),
                            DateDeleted = new DateTime(2024, 12, 26, 14, 0, 46, 302, DateTimeKind.Local).AddTicks(7915),
                            DateOfBirth = new DateTime(1990, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 12, 26, 14, 0, 46, 302, DateTimeKind.Local).AddTicks(7912),
                            FirstName = "John",
                            Gender = "Male",
                            LastName = "Doe",
                            NickName = "Johnny",
                            Place = "New York",
                            Position = 1,
                            Salary = 50000.0,
                            Status = "Active",
                            loacation = ""
                        },
                        new
                        {
                            Id = new Guid("7288f590-3256-4b1e-89df-b7554cef8349"),
                            DateCreated = new DateTime(2024, 12, 26, 14, 0, 46, 302, DateTimeKind.Local).AddTicks(7945),
                            DateDeleted = new DateTime(2024, 12, 26, 14, 0, 46, 302, DateTimeKind.Local).AddTicks(7945),
                            DateOfBirth = new DateTime(1985, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 12, 26, 14, 0, 46, 302, DateTimeKind.Local).AddTicks(7945),
                            FirstName = "Jane",
                            Gender = "Female",
                            LastName = "Smith",
                            NickName = "Janey",
                            Place = "London",
                            Position = 0,
                            Salary = 60000.0,
                            Status = "Inactive",
                            loacation = ""
                        });
                });

            modelBuilder.Entity("Data.Model.Note", b =>
                {
                    b.HasOne("Data.Model.Staff", "Staff")
                        .WithMany("notes")
                        .HasForeignKey("StaffId");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Data.Model.Staff", b =>
                {
                    b.Navigation("notes");
                });
#pragma warning restore 612, 618
        }
    }
}
