// <auto-generated />
using System;
using API.ApplicationDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(StaffDbContext))]
    partial class StaffDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Model.Notes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5512791e-3f36-40a7-99ac-a4f58794ae56"),
                            DateCreated = new DateTime(2024, 12, 29, 20, 12, 10, 924, DateTimeKind.Local).AddTicks(2090),
                            Text = "Welcome Note"
                        },
                        new
                        {
                            Id = new Guid("29ce6ef4-7b11-4fe1-b252-ed67f8ddfb75"),
                            DateCreated = new DateTime(2024, 12, 29, 20, 12, 10, 924, DateTimeKind.Local).AddTicks(2092),
                            Text = "Take note"
                        });
                });

            modelBuilder.Entity("Data.Model.Staffs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Salary")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loacation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1e1cced-fb23-4883-8f73-beb4562f1b77"),
                            DateCreated = new DateTime(2024, 12, 29, 20, 12, 10, 924, DateTimeKind.Local).AddTicks(1751),
                            DateDeleted = new DateTime(2024, 12, 29, 20, 12, 10, 924, DateTimeKind.Local).AddTicks(1769),
                            DateOfBirth = new DateTime(1990, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 12, 29, 20, 12, 10, 924, DateTimeKind.Local).AddTicks(1765),
                            FirstName = "John",
                            Gender = "Male",
                            LastName = "Doe",
                            NickName = "Johnny",
                            Place = "New York",
                            Position = "Developer",
                            Salary = 50000.0,
                            Status = "Active",
                            loacation = ""
                        },
                        new
                        {
                            Id = new Guid("46ea3448-7dc9-49b5-81b2-0e6cd155c93c"),
                            DateCreated = new DateTime(2024, 12, 29, 20, 12, 10, 924, DateTimeKind.Local).AddTicks(1817),
                            DateDeleted = new DateTime(2024, 12, 29, 20, 12, 10, 924, DateTimeKind.Local).AddTicks(1817),
                            DateOfBirth = new DateTime(1985, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 12, 29, 20, 12, 10, 924, DateTimeKind.Local).AddTicks(1817),
                            FirstName = "Jane",
                            Gender = "Female",
                            LastName = "Smith",
                            NickName = "Janey",
                            Place = "London",
                            Position = "Manager",
                            Salary = 60000.0,
                            Status = "Inactive",
                            loacation = ""
                        },
                        new
                        {
                            Id = new Guid("c4d5b576-083c-4195-82b1-186e818cbc42"),
                            DateCreated = new DateTime(2024, 12, 29, 20, 12, 10, 924, DateTimeKind.Local).AddTicks(1821),
                            DateDeleted = new DateTime(2024, 12, 29, 20, 12, 10, 924, DateTimeKind.Local).AddTicks(1822),
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 12, 29, 20, 12, 10, 924, DateTimeKind.Local).AddTicks(1822),
                            FirstName = "John",
                            Gender = "",
                            LastName = "Doe",
                            NickName = "Johnny",
                            Place = "New York",
                            Position = "Designer",
                            Salary = 55000.0,
                            Status = "Active",
                            loacation = ""
                        },
                        new
                        {
                            Id = new Guid("efcca54e-3103-4dcd-a0be-4ef927435384"),
                            DateCreated = new DateTime(2024, 12, 29, 20, 12, 10, 924, DateTimeKind.Local).AddTicks(1838),
                            DateDeleted = new DateTime(2024, 12, 29, 20, 12, 10, 924, DateTimeKind.Local).AddTicks(1838),
                            DateOfBirth = new DateTime(1987, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 12, 29, 20, 12, 10, 924, DateTimeKind.Local).AddTicks(1838),
                            FirstName = "Alice",
                            Gender = "",
                            LastName = "Johnson",
                            NickName = "Ally",
                            Place = "Los Angeles",
                            Position = "tester",
                            Salary = 70000.0,
                            Status = "Active",
                            loacation = ""
                        },
                        new
                        {
                            Id = new Guid("5a898d4a-dd98-4eca-abd6-626db58a1ba4"),
                            DateCreated = new DateTime(2024, 12, 29, 20, 12, 10, 924, DateTimeKind.Local).AddTicks(1841),
                            DateDeleted = new DateTime(2024, 12, 29, 20, 12, 10, 924, DateTimeKind.Local).AddTicks(1842),
                            DateOfBirth = new DateTime(1992, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 12, 29, 20, 12, 10, 924, DateTimeKind.Local).AddTicks(1842),
                            FirstName = "Bob",
                            Gender = "",
                            LastName = "Brown",
                            NickName = "Bobby",
                            Place = "San Francisco",
                            Position = "Developer",
                            Salary = 65000.0,
                            Status = "Inactive",
                            loacation = ""
                        });
                });

            modelBuilder.Entity("Data.Model.Notes", b =>
                {
                    b.HasOne("Data.Model.Staffs", "Staff")
                        .WithMany("notes")
                        .HasForeignKey("StaffId");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Data.Model.Staffs", b =>
                {
                    b.Navigation("notes");
                });
#pragma warning restore 612, 618
        }
    }
}
